version: '3.8'

services:
  frontend:
    build: 
      context: ./virtualisation
    ports:
      - "8080:80"
 

  backend:
    build: 
      context: ./virtualisation_back
    ports:
      - "13000:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=leomessi
      - POSTGRES_DB=virtualisation
    depends_on:
      - db
    

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: leomessi
      POSTGRES_DB: virtualisation
    ports:
      - "5432:5432"
    

